config/routes.rb
Rails.application.routes.draw do
  resources :animals
  devise_for :users
  root to: 'animals#index'
  get '/search' , to: 'animals#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :user
  paginates_per 5
  validates :title, presence: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :animals
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: [:show, :edit, :update, :destroy]

  # GET /animals
  # GET /animals.json
  def index
    @animals = Animal.order(:name).page params[:page]
  end

  def search
      if params[:q].blank?
       'Please input search word'
      else
        @animals = Animal.where("lower(title) LIKE lower(?)", "%" + params[:q] + "%")
      end
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals
  # POST /animals.json
  def create
    @animal = Animal.new(animal_params)
    @animal.user = current_user

    respond_to do |format|
      if @animal.save
          format.html { redirect_to @animal, notice: 'Animal was successfully created.' }
          format.json { render :show, status: :created, location: @animal }
      else
          format.html { render :new }
          format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

    # PATCH/PUT /animals/1
    # PATCH/PUT /animals/1.json
    def update
      respond_to do |format|
        if @animal.update(animal_params)
          format.html { redirect_to @animal, notice: 'Animal was successfully updated.' }
          format.json { render :show, status: :ok, location: @animal }
        else
          format.html { render :edit }
          format.json { render json: @animal.errors, status: :unprocessable_entity }
        end
      end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to animals_url, notice: 'Animal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def animal_params
      params.require(:animal).permit(:title, :color, :amount, :user_id)
    end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animals/_form.html.erb
<%= form_with(model: animal, local: true) do |form| %>
  <% if animal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
      <% animal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/animals/edit.html.erb
<h1>Editing Animal</h1>

<%= render 'form', animal: @animal %>

<%= link_to 'Show', @animal %> |
<%= link_to 'Back', animals_path %>

app/views/animals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Animals <p><%=link_to 'Logout', destroy_user_session_path , method: :delete %></p></h1>

<form class="form-inline my-2 my-lg-0" action="/search">
  <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search">
  <button class="btn btn-outline-danger my-2 my-sm-0" type="submit">Search</button>
</form>

<table>
  <thead>
    <div class="animal-title">
      <tr>
        <th>Title</th>
        <th>Color</th>
        <th>Amount</th>
        <th>User Email</th>
        <th colspan="3"></th>
      </tr>
    </div>
  </thead>

  <tbody>
    <div align="center">
      <%= paginate @animals %>
    </div>
    <div class="animal-body">
      <% @animals.each do |animal| %>
        <tr>
          <td><%= animal.title %></td>
          <td><%= animal.color %></td>
          <td><%= animal.amount %></td>
          <td><%= animal.user.email %></td>
          <td><%= link_to 'Show', animal %></td>
          <td><%= link_to 'Edit', edit_animal_path(animal) %></td>
          <td><%= link_to 'Destroy', animal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </div>

  </tbody>
</table>
<div align="center">
  <%= paginate @animals %>
</div>
<br>

<p><%= link_to 'New Animal', new_animal_path %></p>

app/views/animals/new.html.erb
<h1>New Animal</h1>

<%= render 'form', animal: @animal %>

<%= link_to 'Back', animals_path %>

app/views/animals/search.html.erb
<h3>Search Result</h3>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Color</th>
      <th>Amount</th>
      <th>User Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% if @animals.blank? %>
 		 <%= "Such animal can't be found" %>
		<% else %>
		 <tr>
 		 <% @animals.each do |animal| %>
 		   <td><%= animal.title %></td>
		   <td><%= animal.color %></td>
		   <td><%= animal.amount %></td>
       <td><%= animal.user.email %></td>

		 </tr>
     <% end %>
    <% end %>
  </tbody>
</table>

app/views/animals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @animal.title %>
</p>

<p>
  <strong>Color:</strong>
  <%= @animal.color %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @animal.amount %>
</p>

<p>
  <strong>UserEmail:</strong>
  <%= @animal.user.email %>
</p>

<%= link_to 'Edit', edit_animal_path(@animal) %> |
<%= link_to 'Back', animals_path %>

app/views/layouts/_messages.html.erb
<% if notice %>
  <div class='alert alert-success'>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class='alert alert-danger'>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= alert %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZooApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class = "container jumbotron">
      <%= yield %>
    </div>
  </body>
</html>